### ISSUE TITLE
Docker-compose example?

### ISSUE THREAD

**Issue by gurabli** [joshuaavalon/docker-cloudflare#30]
I'm trying to tun this with docker-compose, but having some troubles.

```
  cloudflareddns:
    image: joshava/cloudflare-ddns
    container_name: cloudflare-ddns
    environment:
      - TZ=EUROPE/BUDAPEST
    volumes:
      - "/opt/appdata/cloudflareddns/:/app/config.yaml"
```
I have the config.yaml created in the opt/appdata/cloudflareddns folder. If I build the container, it start, but have the following error, repeating:

2019-11-26T18:16:54.304Z [INFO ]: Cloudflare DDNS start
2019-11-26T18:16:54.315Z [ERROR]: EISDIR: illegal operation on a directory, read
2019-11-26T18:16:54.316Z [INFO ]: Cloudflare DDNS end

The yaml looks like this:

```
auth:
  scopedToken: TOKEN
domains:
  - name: example.com
    type: A
    proxied: true
    create: true
    zoneId: cflkdflkdkflkdmfkdmflk
```
Thanks for your help!
