### ISSUE TITLE
[Feature] Add support for setting IP Address in Config

### ISSUE THREAD

**Issue by dunklesToast** [joshuaavalon/docker-cloudflare#49]
**Is your feature request related to a problem? Please describe.**
We want to use this container to persist our Cloudflare Configuration in a Repo. While having the DDNS Service is nice, we also want to set Records for Servers that have static IP Addresses. I have not found a way to define this. Also, it would be awesome if more types would be supported. For Example TXT or MX.

**Describe the solution you'd like**
Add a new field called `value` and add support for MX, TXT, CNAME and so on.

```yml
auth:
  scopedToken: suchToken
domains:
  - name: my-awesome-page.de
    type: A
    proxied: false
    create: true
    value: 1.1.1.1
    zoneId: suchId
  - name: my-awesome-page.de
    type: TXT
    proxied: false
    create: true
    value: google-site-verification=x
    zoneId: suchId
```

**Additional context**
I could probably open a PR with the features if wanted.
