### ISSUE TITLE
[Bug] [warn] Fail to fetch ip from https://v4.ident.me/.json. (Unexpected token . in JSON at position 5)

### ISSUE THREAD

**Issue by L3H0** [joshuaavalon/docker-cloudflare#53]
**Describe the bug**
When i want update the IP address of my Cloudflare DNS i got this error.

**To Reproduce**
Run docker and check.
My config:
```
ipv4:
  - type: json
    url: https://v4.ident.me/.json
    fields:
      - address
  - type: json
    url: https://api.ipify.org?format=json
    fields:
      - ip 
```

**Expected behavior**
Run container without this error.

**Output log**
08:20:01.824Z [warn] Fail to fetch ip from https://v4.ident.me/.json. (Unexpected token . in JSON at position 5)
08:20:01.841Z [warn] Fail to fetch ip from https://v4.ident.me/.json. (Unexpected token . in JSON at position 5)
08:20:01.850Z [warn] Fail to fetch ip from https://v4.ident.me/.json. (Unexpected token . in JSON at position 5)

**Environment:**
- OS: Synology DSM 6.2
- Docker:  20.10.3

**Additional context**

**Comment by joshuaavalon** [comment]
`v4.ident.me` now responses plain text but it is not hosted by me. So, it is not my bug.

You can do 1 of the followings:

1. Change the configuration because it now returns plain text.

```yaml
ipv4:
  - type: text
    url: https://v4.ident.me/
```

2. Use Cloudflare Api which should not change

```
type: ini
url: https://1.1.1.1/cdn-cgi/trace
field: ip
```

3. Host you own IP echo service.
