### ISSUE TITLE
[Bug] DNS records gets duplicated and not updated

### ISSUE THREAD

**Issue by Romanicus** [joshuaavalon/docker-cloudflare#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

2.8-

### Describe The Bug

Hi, since a few weeks my dns records doesn't get updated. Instead the same entry with another IP is created 
![Bildschirmfoto 2021-11-30 um 15 58 56](https://user-images.githubusercontent.com/6033435/144071572-ff551e7d-8a31-464b-98bb-41b4e52164cb.png). This leads to non functional dns entries.

Configuration is attached.

I have double checked that my Cloudflare API-Keys have valid options (the same as in the readme).

### Steps To Reproduce

Just let the program run with my config.

### Expected Behavior

The entries in Cloudflare should be overwritten and not be doubled.

### YAML Configuration

```yaml
auth:
  scopedToken: TOKEN
domains:
  - name: plex
    type: A
    proxied: true
    create: true
    zoneId: ZONEID
  - name: proxmox
    type: A
    proxied: true
    create: true
    zoneId: ZONEID
  - name: nas
    type: A
    proxied: true
    create: true
    zoneId: ZONEID
```
