### ISSUE TITLE
Not IPv4

### ISSUE THREAD

**Issue by MaiSuiMiao** [joshuaavalon/docker-cloudflare#56]
Hello, because my client has multiple ip addresses, so I used the following configuration to get my IP , but why is it prompted that it is not an IPV4 address? What should be the correct format?

This is my configure file:
```
auth:
  scopedToken: ABCDEFG
domains:
  - name: ddns.example.com
    type: A
    proxied: false
    create: true
    zoneId: HIJKLMN
ipv4:
  - type: text
    url: https://ip.3322.net
```
Sensitive fields have been cleared

![20211215025754](https://user-images.githubusercontent.com/10583191/146062474-3c3e7dff-2b98-4328-88a7-13c4b0341aae.png)

ip.3322.net output a string like this:
![20211215030759](https://user-images.githubusercontent.com/10583191/146063554-83391d52-eb01-404c-9b73-f5ffc60ef5f3.png)

**Comment by joshuaavalon** [comment]
It is parsed by Node.js standard library.

https://github.com/joshuaavalon/docker-cloudflare/blob/67274e15ae08f5d9a96bdc4d8caaadcb3abf8d9d/packages/app/src/ip.ts#L3-L18

From the log, I guess it also return line break at the end because the `)` go to the next line.

**Comment by MaiSuiMiao** [comment]
What should I do? I took a look and it did output a return line break

**Comment by MaiSuiMiao** [comment]
![20211215161938](https://user-images.githubusercontent.com/10583191/146150283-51c58417-83b9-4143-b329-8000446647ed.png)
If I use the default method to get the ip, the result is probably the above

**Comment by joshuaavalon** [comment]
I add an option `trim` to development branch. Can you try if it works for you?

```yaml
ipv4:
  - type: text
    url: https://ip.3322.net
    trim: true
```

https://github.com/joshuaavalon/docker-cloudflare/pkgs/container/cloudflare-ddns/11920613?tag=develop
