### ISSUE TITLE
[Bug] Every now and then this container uses in excess of 2GB of RAM

### ISSUE THREAD

**Issue by ovizii** [joshuaavalon/docker-cloudflare#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

latest

### Describe The Bug

I usually limit containers which might get out of hand in terms of RAM and CPU. Out of habit I also did this for your container with these limits enforced:

```
    cpu_count: 1                                                                                                                                     
    mem_limit: 1G
```            

and about 1-2 a month, this container runs out of memory hence I am wondering what it could use this much RAM for? btw. I have been using this image for more than a year and this behaviour has only recently started to happen.

I usually get warned by my monitoring setup:
![image](https://user-images.githubusercontent.com/837902/148656746-da5a77c7-1029-4016-b9af-c69e08107e0a.png)

followed by:
![image](https://user-images.githubusercontent.com/837902/148656768-c3b08364-d171-4679-8aff-1a88e80facb2.png)





### Steps To Reproduce

use this docker-compose.yml:

```
version: '2.4'                                                                                                                                       
                                                                                                                                                     
services:                                                                                                                                            
                                                                                                                                                     
# https://github.com/joshuaavalon/docker-cloudflare                                                                                                  
                                                                                                                                                     
  cloudflare-ddns:                                                                                                                                   
    container_name: cloudflare-ddns                                                                                                                  
    image: joshava/cloudflare-ddns:latest                                                                                                            
    hostname: cloudflare-ddns                                                                                                                        
    network_mode: bridge                                                                                                                             
    volumes:                                                                                                                                         
      - ./config.yaml:/app/config.yaml                                                                                                               
    restart: "no"                                                                                                                                    
    environment:                                                                                                                                     
      - PUID=1000                                                                                                                                    
      - PGID=1000                                                                                                                                    
    cpu_count: 1                                                                                                                                                                                                                                                
    mem_limit: 1G                           
```

### Expected Behavior

run with minimal RAM usage

### YAML Configuration

_No response_

### JS Configuration

_No response_

### Relevant Output Log

```shell
I can only see lines of "updated" and "skipped" in the logs
```

**Comment by joshuaavalon** [comment]
Can you try to use `docker exec` to enter the docker and inspect what is using up the ram?

Because there are no code running in idle. My guess is either the Docker log or crond.

**Comment by ovizii** [comment]
OK, lets see. Currently it shows it is using  979M / 1G 

top looks like this:

![image](https://user-images.githubusercontent.com/837902/148736489-05145bd6-1cc1-49f6-8a70-7997bbaf9332.png)

pstree
```
pstree                                                                                                                                     
s6-svscan-+-s6-supervise                                                                                                                             
          `-s6-supervise---sh---crond---36*[node---10*[{node}]]   
```

I can try and run a tagged version if you have no further ideas what to look at for now?

**Comment by joshuaavalon** [comment]
It seems like s6 is starting multiple process of the script and not exiting. I will try to reproduce on my side.  Can you check if you are use 2.9.0 by checking the image hash?

**Comment by joshuaavalon** [comment]
I have just tried `2.9.0` for a while. The are no node processes when idle. The container does not use more than 100 MB of memory.

It would be nice if you can provide the log and config (masking the IP and domain) and the environment that you are running on.

**Comment by ovizii** [comment]
You asked about the environment, I guess this is what you need. I'm running this on my NAS at home which runs:

```
lsb_release -a                                                                                               
No LSB modules are available.                                                                                                                        
Distributor ID: Debian                                                                                                                               
Description:    Debian GNU/Linux 11 (bullseye)                                                                                                       
Release:        11                                                                                                                                   
Codename:       bullseye
```      

```
docker -v                                                                                                    
Docker version 20.10.12, build e91ed57
```

```
docker-compose -v                                                                                            
docker-compose version 1.29.0, build 07737305 
```

I did a docker inspect cloudflare-ddns and found the current image hash: 

"Image": "sha256:586e2d02ba5cb08a5dc647287aa2eb238ffe1d29b08e4cc0679151f6bf30fb3a"

unfortunately I can't figure out to which version this corresponds. (I've checked your latest, 2.9 and 2 tags and this is none of them) - I've left my instance running in case you have more ideas how to figure this one out.

The logs don't say much except recurring lines like these, either updating a DNS record or skipping it every 5 minutes apparently.

```
{"log":"2022-01-10T16:40:05.896Z [info] Skipped updating.\n","stream":"stdout","time":"2022-01-10T16:40:05.896135174Z"}     
                           
{"log":"2022-01-10T16:40:05.896Z [info] Updated sub1.domain.tld with  84.185.164.xxx\n","stream":"stdout","time":"2022-01-10T16:40:05.896189195Z"}  
 
{"log":"2022-01-10T16:40:12.768Z [info] Skipped updating.\n","stream":"stdout","time":"2022-01-10T16:40:12.768714385Z"}   
                             
{"log":"2022-01-10T16:40:12.768Z [info] Updated sub2.domain.tld with 84.185.164.xxx\n","stream":"stdout","time":"2022-01-10T16:40:12.768777965Z"}  
   
{"log":"2022-01-10T16:40:12.768Z [info] Cloudflare DDNS end\n","stream":"stdout","time":"2022-01-10T16:40:12.768783906Z"} 
```
I have only masked the last 3 digits of the IP and the domains and haven't touched anything else in this log file.

I'm ready to switch to docker pull joshava/cloudflare-ddns:2 whenever you say there isn't more info to be found through my current running isntance.

**Comment by joshuaavalon** [comment]
> sha256:586e2d02ba5cb08a5dc647287aa2eb238ffe1d29b08e4cc0679151f6bf30fb3a

I also cannot find the version that you can using. Can you try the latest version (`2.9`)?

Also, can you provide the configuration that you are using (masking out domain)?
Then, I can try to spin up a VM to try to reproduce it.

**Comment by ovizii** [comment]
I don't understand where this image hash comes from either :-( 
```
docker inspect cloudflare-ddns | grep Image                                                                                  
        "Image": "sha256:586e2d02ba5cb08a5dc647287aa2eb238ffe1d29b08e4cc0679151f6bf30fb3a",                                                          
            "Image": "joshava/cloudflare-ddns:latest",      
```

I have now switched to the 2.9.0 tag, lets see if the issue will occur again. 

Here is my config.yaml (its very simple. I've cut it down to this although I have a few more subdomains of the same domain in there).

```
auth:                                                                                                                                                
  scopedToken: M-my-secret-token-4                                                                                              
domains:                                                                                                                                             
  - name: "sub1.domain.tld"                                                                                                                            
    type: A                                                                                                                                          
    proxied: false                                                                                                                                   
    create: true                                                                                                                                     
    zoneId: my-secret-zone-id                                                                                                         
  - name: "sub2.domain.tld"                                                                                                                           
    type: A                                                                                                                                          
    proxied: false                                                                                                                                   
    create: true                                                                                                                                     
    zoneId: my-secret-zone-id 
```

**Comment by ovizii** [comment]
so I've been running with image: joshava/cloudflare-ddns:2.9 since yesterday and right now the container says its using about 400GB of RAM.

Looking inside I see:

![image](https://user-images.githubusercontent.com/837902/149094315-7e23ca22-32ca-4384-bdd4-96797953c64b.png)


and 

```
bash-5.1# pstree                                                                                                                                     
s6-svscan-+-s6-supervise                                                                                                                             
          `-s6-supervise---sh---crond---11*[node---10*[{node}]]     
```

here's my docker-compose-yml

```
version: '2.4'                                                                                                                                       
                                                                                                                                                     
services:                                                                                                                                            
                                                                                                                                                     
# https://github.com/joshuaavalon/docker-cloudflare                                                                                                  
                                                                                                                                                     
  cloudflare-ddns:                                                                                                                                   
    container_name: cloudflare-ddns                                                                                                                  
    image: joshava/cloudflare-ddns:2.9                                                                                                               
    hostname: cloudflare-ddns                                                                                                                        
    network_mode: bridge                                                                                                                             
    volumes:                                                                                                                                         
      - ./config.yaml:/app/config.yaml                                                                                                               
    restart: "no"                                                                                                                                    
    environment:                                                                                                                                     
      - PUID=1000                                                                                                                                    
      - PGID=1000                                                                                                                                    
    cpu_count: 1                                                                                                                                                                                                                                                                   
    mem_limit: 1G              
```

**Comment by joshuaavalon** [comment]
![image](https://user-images.githubusercontent.com/7152420/149172889-e9561f2d-c878-46b5-b9a5-88fd37cd34e5.png)

I am been running it from yesterday and it only using less than 50MB.

Here is my `docker-compose.yml`

```yaml
version: "3"

services:
  ddns:
    image: joshava/cloudflare-ddns:2.9
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
```

```yaml
auth:
  scopedToken: <TOKEN_ID>
domains:
  - name: example2.com
    type: A
    proxied: true
    create: true
    zoneId: <ZONE_ID>
  - name: example.com
    type: A
    proxied: true
    create: true
    zoneId: <ZONE_ID>
```

I really do not what is causing your problem. 

https://github.com/joshuaavalon/docker-cloudflare/blob/a6dd5af46f0dbf65e08bb681c40b0b15e177edfe/packages/app/src/index.ts#L104-L112

`Cloudflare DDNS end` is the end of script. I do not know what is causing the script not exiting.

**Comment by ovizii** [comment]
don't worry and thanks about your help. I will try and remove my memory and CPU limits and switch from docker-compose version 2.4 to 3.8 - lets see if that makes any difference.

**Comment by ovizii** [comment]
OK, I am giving up. Thanks for your help trying to figure it out but I am still getting this RAM usage even with docker-compose version 3.8 and your image version 2.9 without any limits. Without RAM limits the container won't become "out of memory" and retsarted.

Current docker-compose.yml

```
version: '3.8'                                                                                                                                                                                                                                                                                            
services:                                                                                                                                            
                                                                                                                                                     
# https://github.com/joshuaavalon/docker-cloudflare                                                                                                  
                                                                                                                                                     
  cloudflare-ddns:                                                                                                                                   
    container_name: cloudflare-ddns                                                                                                                  
    image: joshava/cloudflare-ddns:2.9                                                                                                               
    hostname: cloudflare-ddns                                                                                                                        
    network_mode: bridge                                                                                                                             
    volumes:                                                                                                                                         
      - ./config.yaml:/app/config.yaml                                                                                                               
    restart: "no"                                                                                                                                    
    environment:                                                                                                                                     
      - PUID=1000                                                                                                                                    
      - PGID=1000                  
```

RAM usage after roundabout 24h via docker stats cloudflare-ddns
```
CONTAINER ID   NAME              CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O   PIDS                                          
e6765bfb2045   cloudflare-ddns   0.00%     451.2MiB / 125.7GiB   0.35%     77.4MB / 25MB   0B / 0B     269                                           
```
