### ISSUE TITLE
[Feature] Support for multi-line yaml anchors in config

### ISSUE THREAD

**Issue by aleksandarmomic** [joshuaavalon/docker-cloudflare#59]
Because domain entries are mostly repetitive, it would be nice to support multi-line anchors to avoid copy pasting.
When using multi-line yaml anchors, the schema validator throws errors in logs and keeps trying to validate the yaml.
I created a `default` anchor to be used everywhere and in the second domain I just override the name which is valid yaml, but does not get parsed by the app.

This is the example config I made:
```yaml
auth:
  scopedToken: <scoped-token>
domains:
  - &default
    name: <domain>
    type: A
    proxied: false
    create: true
    zoneId: <zone-id>

  - <<: *default
    name: <domain2>
```

The error that gets thrown:
```yaml
{
  data: {
    auth: { scopedToken: '<scoped-token>' },
    domains: [ [Object], [Object] ]
  },
  schema: {
    '$id': 'https://joshuaavalon.github.io/docker-cloudflare/config.schema.json',
    '$schema': 'http://json-schema.org/draft-07/schema#',
    description: 'Configuration for docker-cloudflare',
    type: 'object',
    properties: {
      api: [Object],
      logLevel: [Object],
      auth: [Object],
      domains: [Object],
      ipv4: [Object],
      ipv6: [Object],
      echoParsers: [Object]
    },
    required: [ 'auth', 'domains' ],
    additionalProperties: false,
    definitions: {
      globalAuth: [Object],
      scopedAuth: [Object],
      domain: [Object],
      ipEcho: [Object],
      ipEchoParser: [Object],
      webhook: [Object]
    }
  }
}

/app/packages/schema/lib/index.js:37
    throw new SchemaViolationError(validate.errors || []);
          ^

SchemaViolationError: Failed to validate schema Errors:
must NOT have additional properties
    at verifySchema (/app/packages/schema/lib/index.js:37:11)
    at readFileConfig (/app/packages/config/lib/file-config.js:30:47)
    at async readConfig (/app/packages/config/lib/index.js:21:24)
    at async main (/app/packages/app/lib/index.js:80:20) 
    {
  errors: [
    {
      instancePath: '/domains/1',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: { additionalProperty: '<<' },
      message: 'must NOT have additional properties'
    }
  ]
}
```

I think the solution is obvious, schema needs to be updated.

As a side note:
The schema id in the logs is not a valid url, maybe it just needs to be updated to the new location? 
- [https://github.com/joshuaavalon/docker-cloudflare/blob/master/packages/config/src/config.schema.json](https://github.com/joshuaavalon/docker-cloudflare/blob/master/packages/config/src/config.schema.json)

When I throw in to vscode to use the valid schema url, it doesn't complain.
