### ISSUE TITLE
[Bug] Unclear how to use cron under config.yaml

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [joshuaavalon/docker-cloudflare#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

2.9.2

### Describe The Bug

I'm using the latest version with a config.yaml.  I can't figure out where to place the `cron` directive and, if I understand the README, environment variables are deprecated and ignored if a config.yaml is present.

I've tried placing the cron directive in a few places, and it fails verification when the container starts.

### Steps To Reproduce

1.  configure the container to use the config.yaml
2. add a cron directive at the base level of the directives

### Expected Behavior

Clarity on where the cron directive should be placed in the config.yaml.

### YAML Configuration

```yaml
pi: https://api.cloudflare.com/client/v4/
logLevel: info
auth:
  scopedToken: <token>
domains:
  - name: <domain>
    type: A
    proxied: false
    create: true
    zoneId: <zoneid>
    # webhook:
    #  run: https://example.com/webhook/start
    #  success: https://example.com/webhook/success
    #  failure: https://example.com/webhook/failure
ipv4:
  - type: json
    url: https://v4.ident.me/.json
    fields:
      - address
  - type: json
    url: https://api.ipify.org?format=json
    fields:
      - ip

cron: */5 * * * *
```

### Relevant Output Log

```shell
cloudflare-ddns    | YAMLSyntaxError: YAML Error in /app/config.yaml:
cloudflare-ddns    | All collection items must start at the same column at line 1, column 1:
cloudflare-ddns    | 
cloudflare-ddns    | api: https://api.cloudflare.com/client/v4/
cloudflare-ddns    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^…
cloudflare-ddns    | 
cloudflare-ddns    |     at Collection.parse (/app/node_modules/yaml/dist/parse-cst.js:331:24)
cloudflare-ddns    |     at /app/node_modules/yaml/dist/parse-cst.js:1605:29
cloudflare-ddns    |     at Document.parseContents (/app/node_modules/yaml/dist/parse-cst.js:622:26)
cloudflare-ddns    |     at Document.parse (/app/node_modules/yaml/dist/parse-cst.js:685:19)
cloudflare-ddns    |     at Object.parse (/app/node_modules/yaml/dist/parse-cst.js:1729:18)
cloudflare-ddns    |     at parseDocument (/app/node_modules/yaml/dist/index.js:43:24)
cloudflare-ddns    |     at Object.parse (/app/node_modules/yaml/dist/index.js:55:15)
cloudflare-ddns    |     at loadYaml (/app/node_modules/cosmiconfig/dist/loaders.js:44:25)
cloudflare-ddns    |     at Explorer.loadFileContent (/app/node_modules/cosmiconfig/dist/Explorer.js:84:32)
cloudflare-ddns    |     at Explorer.createCosmiconfigResult (/app/node_modules/cosmiconfig/dist/Explorer.js:89:36) {
cloudflare-ddns    |   nodeType: 'MAP',
cloudflare-ddns    |   range: Range { start: 0, end: 597 },
cloudflare-ddns    |   linePos: { start: { line: 1, col: 1 }, end: { line: 26, col: 1 } }
cloudflare-ddns    | }
```

**Comment by joshuaavalon** [comment]
First,  it should be `api` not `pi` on the first line.

Also, you don't need full configuration. You only need to set what you need and leave other to default. Here is an example from README.

```yaml
auth:
  scopedToken: QPExdfoNLwndJPDbt4nK1-yF1z_srC8D0m6-Gv_h
domains:
  - name: foo.example.com
    type: A
    proxied: true
    create: true
    zoneId: JBFRZWzhTKtRFWgu3X7f3YLX
```

Second, the log 
> YAMLSyntaxError: YAML Error in /app/config.yaml:
> All collection items must start at the same column at line 1, column 1:

Please check the YAML syntax in your config. You can use support text editor or any online syntax checker.

From the error message, you probably does not indent the config file correctly.

Also, `cron: */5 * * * *` is not valid YAML. `*` is reserved character, you must use `"`, e.g. `cron: "*/5 * * * *"`.

If you are not familiar to YAML, I recommend you to use JSON instead. You can set the config path via `CLOUDFLARE_CONFIG` in environment variables.
