### ISSUE TITLE
[help] Unclear on env configuration

### ISSUE THREAD

**Issue by yorickdowne** [joshuaavalon/docker-cloudflare#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.0.0

### Describe The Bug

I am unclear on how to use ENV variables. When I start the docker container with ENV variables defined and no config.yaml, it complains it cannot find /app/config.yaml. I did not, in docs, see a command line switch or ENV variable to turn this behavior off. Setting CF_DNS_CONFIG and CLOUDFLARE_CONFIG to blank values did not resolve.

### Steps To Reproduce

Run in docker without a config.yaml file, with environment variables defined where they differ from defaults.

### Expected Behavior

App starts and does not look for config.yaml

**Comment by joshuaavalon** [comment]
I cannot help you if you do not post your docker-compose YAML. But it seems like you are missing `_`. There is `_` and `__` in configuration.

```yaml
version: "3"

services:
  ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:3.0.0
    restart: unless-stopped
    environment:
      - CF_DNS__CRON=*/10 * * * *
      - CF_DNS__AUTH__SCOPED_TOKEN=<TOKEN>
      - CF_DNS__DOMAINS_0__NAME=example.com
      - CF_DNS__DOMAINS_0__TYPE=A
      - CF_DNS__DOMAINS_0__ZONE_ID=<ZONE_ID>
      - CF_DNS__DOMAINS_0__PROXIED=true
      - CF_DNS__DOMAINS_0__CREATE=true
```

`CF_DNS__` is the prefix.
If it is the same word, it is separated by `_`; If it is different level, it is separated by `__`.

For example, `CF_DNS__AUTH__SCOPED_TOKEN=<TOKEN>` is
```yaml
auth:
  scopedToken: <TOKEN>
```

**Comment by yorickdowne** [comment]
Fair comment. Here's the compose:

```
  cf-ddns-v4:
    image: joshava/cloudflare-ddns:latest
    restart: "unless-stopped"
    environment:
      - CF_DNS__LOG_LEVEL=${LOG_LEVEL:-info}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_API_TOKEN}
      - CF_DNS__DOMAINS_0__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_0__NAME=${DDNS_SUBDOMAIN}
      - CF_DNS__DOMAINS_0__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_0__CREATE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

And the log output:

```
traefik-cf-ddns-v4-1  | node:internal/process/promises:279
traefik-cf-ddns-v4-1  |             triggerUncaughtException(err, true /* fromPromise */);
traefik-cf-ddns-v4-1  |             ^
traefik-cf-ddns-v4-1  | 
traefik-cf-ddns-v4-1  | [Error: ENOENT: no such file or directory, open '/app/config.yaml'] {
traefik-cf-ddns-v4-1  |   errno: -2,
traefik-cf-ddns-v4-1  |   code: 'ENOENT',
traefik-cf-ddns-v4-1  |   syscall: 'open',
traefik-cf-ddns-v4-1  |   path: '/app/config.yaml'
traefik-cf-ddns-v4-1  | }
```

What I expected was that if there is no config file, it'll run from ENV variables; if there is a config file, it'll use it.
