### ISSUE TITLE
[Bug] One of the v6 parsers does not work

### ISSUE THREAD

**Issue by yorickdowne** [joshuaavalon/docker-cloudflare#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.0.0

### Describe The Bug

v6 update shows this warning:

```
Fail to fetch ip from https://[2606:4700:4700::1111]/cdn-cgi/trace. (getaddrinfo ENOTFOUND [2606:4700:4700::1111])
```

I believe this may be because the parser is of type `json` but the output from that URL is not:

```
5316851c499a:/app# curl https://[2606:4700:4700::1111]/cdn-cgi/trace
fl=609f60
h=[2606:4700:4700::1111]
ip=1:2:3:4:5:6:7:8
ts=1682334895.132
visit_scheme=https
uag=curl/7.81.0
colo=FRA
sliver=none
http=http/2
loc=DE
tls=TLSv1.3
sni=off
warp=off
gateway=off
rbi=off
kex=X25519
```

curl was run from within the container to ensure that v6 connectivity is there

### Steps To Reproduce

Set up docker for v6, run docker-cloudflare with AAAA record, observe logs

### Expected Behavior

Fetches IP from both endpoints

### YAML Configuration

```yaml
cf-ddns-v6:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:3
    restart: "unless-stopped"
    environment:
      - CF_DNS__LOG_LEVEL=${LOG_LEVEL:-info}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_DNS_API_TOKEN}
      - CF_DNS__DOMAINS_0__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_0__ZONE_ID=${CF_ZONE_ID:-}
      - CF_DNS__DOMAINS_0__NAME=${DDNS_SUBDOMAIN}
      - CF_DNS__DOMAINS_0__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_0__CREATE=true
      - CF_DNS__DOMAINS_0__TYPE=AAAA
    volumes:
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
```
```


### JS Configuration

_No response_

### Relevant Output Log

```shell
traefik-cf-ddns-v6-1  | [2023-04-24A11:14:15+0000] INFO (234): Cloudflare DDNS start
traefik-cf-ddns-v6-1  | [2023-04-24A11:14:15+0000] WARN (234): Fail to fetch ip from https://[2606:4700:4700::1111]/cdn-cgi/trace. (getaddrinfo ENOTFOUND [2606:4700:4700::1111])
traefik-cf-ddns-v6-1  | [2023-04-24A11:14:17+0000] INFO (234): Started creating.
traefik-cf-ddns-v6-1  | [2023-04-24A11:14:18+0000] INFO (234): Updated ssh.eth-testing with 1:2:3:4:5:6:7:8
traefik-cf-ddns-v6-1  | [2023-04-24A11:14:18+0000] INFO (234): Cloudflare DDNS end
```
```
