### ISSUE TITLE
Unable to start container process in 3.2.0/3.1.0

### ISSUE THREAD

**Issue by JerboaGobi** [joshuaavalon/docker-cloudflare#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.2.0/3.1.0

### Describe The Bug

Unable to start container process: exec: "/app/start.sh": stat /app/start.sh: no such file or directory: unknown

I exported the container and /app/start.sh exists.

Error occurs in 3.2.0 & 3.1.0

Working in 3.0.1

### Steps To Reproduce

1. docker version 24.0.2, build cb74dfc, Docker Compose version v2.18.1
2. See yaml
3. docker compose up -d

### Expected Behavior

Normal startup

### YAML Configuration

```yaml
version: '2.4'

x-service: &service-defaults
  env_file:
    - ./.env
  cpu_shares: 1024
  mem_limit: 256M
  pids_limit: 50
  restart: always
  dns:
    - 172.16.18.1
  security_opt:
    - no-new-privileges:true

x-labels: &labels-defaults
  labels:
    - org.hotio.pullio.update=true

x-logging: &logging-defaults
  logging:
    driver: syslog

services:
  cf-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:latest
    container_name: cf-ddns
    <<: [*service-defaults, *labels-defaults, *logging-defaults]
    volumes:
      - config:/app
    networks:
      macvlan1079:
        ipv4_address: 192.168.1.22
    healthcheck:
      test: ps | grep "s6-supervise cloudflare-ddns" | grep -v grep || exit 1
      interval: 60s
      timeout: 30s
      retries: 5

volumes:
  config:
networks:
  macvlan1079:
    external: true
```

### Relevant Output Log

```shell
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/start.sh": stat /app/start.sh: no such file or directory: unknown
```
