### ISSUE TITLE
[Bug] Record update fails with "no route for that URI"

### ISSUE THREAD

**Issue by yorickdowne** [joshuaavalon/docker-cloudflare#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.2.2

### Describe The Bug

docker-cloudflare 3.2.2 fails to update A and AAAA record with error "no route for that URI". Downgrading docker-cloudflare to 3.1.0 resolves the issue and the updates work.

### Steps To Reproduce

Upgrade a working 3.1.0 deployment to 3.2.2

### Expected Behavior

Records are updated successfully

### YAML Configuration

```yaml
cf-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:3
    restart: "unless-stopped"
    environment:
      - CF_DNS__LOG_LEVEL=${LOG_LEVEL:-info}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_DNS_API_TOKEN}
      - CF_DNS__DOMAINS_0__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_0__ZONE_ID=${CF_ZONE_ID:-}
      - CF_DNS__DOMAINS_0__NAME=${DDNS_SUBDOMAIN}.${DOMAIN}
      - CF_DNS__DOMAINS_0__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_0__CREATE=true
      - CF_DNS__DOMAINS_0__TYPE=A
      - CF_DNS__DOMAINS_1__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_1__ZONE_ID=${CF_ZONE_ID:-}
      - CF_DNS__DOMAINS_1__NAME=${DDNS_SUBDOMAIN}.${DOMAIN}
      - CF_DNS__DOMAINS_1__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_1__CREATE=true
      - CF_DNS__DOMAINS_1__TYPE=AAAA
```

### Relevant Output Log

```shell
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] INFO (28): Cloudflare DDNS start
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] DEBUG (28): Running with the following configuration
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] ERROR (28): Failed to update eth-testing.cryptomanufaktur.net
traefik-cf-ddns-1  |     err: {
traefik-cf-ddns-1  |       "type": "CloudflareApiError",
traefik-cf-ddns-1  |       "message": "Api Error from Cloudflare. Errors: \n{\"code\":7000,\"message\":\"No route for that URI\"}",
traefik-cf-ddns-1  |       "stack":
traefik-cf-ddns-1  |           Error: Api Error from Cloudflare. Errors: 
traefik-cf-ddns-1  |           {"code":7000,"message":"No route for that URI"}
traefik-cf-ddns-1  |               at file:///app/packages/api/lib/create-api/index.js:37:19
traefik-cf-ddns-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
traefik-cf-ddns-1  |               at async getZoneId (file:///app/packages/app/lib/api.js:13:17)
traefik-cf-ddns-1  |               at async updateDns (file:///app/packages/app/lib/api.js:98:20)
traefik-cf-ddns-1  |               at async updateDomain (file:///app/packages/app/lib/index.js:15:20)
traefik-cf-ddns-1  |               at async file:///app/packages/app/lib/index.js:44:28
traefik-cf-ddns-1  |               at async Promise.all (index 0)
traefik-cf-ddns-1  |               at async updateDnsRecords (file:///app/packages/app/lib/index.js:54:5)
traefik-cf-ddns-1  |               at async main (file:///app/packages/app/lib/index.js:74:9)
traefik-cf-ddns-1  |               at async file:///app/index.mjs:5:1
traefik-cf-ddns-1  |       "aggregateErrors": [
traefik-cf-ddns-1  |         {
traefik-cf-ddns-1  |           "type": "Object",
traefik-cf-ddns-1  |           "message": "No route for that URI",
traefik-cf-ddns-1  |           "stack":
traefik-cf-ddns-1  |               
traefik-cf-ddns-1  |           "code": 7000
traefik-cf-ddns-1  |         }
traefik-cf-ddns-1  |       ],
traefik-cf-ddns-1  |       "errors": [
traefik-cf-ddns-1  |         {
traefik-cf-ddns-1  |           "code": 7000,
traefik-cf-ddns-1  |           "message": "No route for that URI"
traefik-cf-ddns-1  |         }
traefik-cf-ddns-1  |       ]
traefik-cf-ddns-1  |     }
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] ERROR (28): Failed to update eth-testing.cryptomanufaktur.net
traefik-cf-ddns-1  |     err: {
traefik-cf-ddns-1  |       "type": "CloudflareApiError",
traefik-cf-ddns-1  |       "message": "Api Error from Cloudflare. Errors: \n{\"code\":7000,\"message\":\"No route for that URI\"}",
traefik-cf-ddns-1  |       "stack":
traefik-cf-ddns-1  |           Error: Api Error from Cloudflare. Errors: 
traefik-cf-ddns-1  |           {"code":7000,"message":"No route for that URI"}
traefik-cf-ddns-1  |               at file:///app/packages/api/lib/create-api/index.js:37:19
traefik-cf-ddns-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
traefik-cf-ddns-1  |               at async getZoneId (file:///app/packages/app/lib/api.js:13:17)
traefik-cf-ddns-1  |               at async updateDns (file:///app/packages/app/lib/api.js:98:20)
traefik-cf-ddns-1  |               at async updateDomain (file:///app/packages/app/lib/index.js:15:20)
traefik-cf-ddns-1  |               at async file:///app/packages/app/lib/index.js:44:28
traefik-cf-ddns-1  |               at async Promise.all (index 1)
traefik-cf-ddns-1  |               at async updateDnsRecords (file:///app/packages/app/lib/index.js:54:5)
traefik-cf-ddns-1  |               at async main (file:///app/packages/app/lib/index.js:74:9)
traefik-cf-ddns-1  |               at async file:///app/index.mjs:5:1
traefik-cf-ddns-1  |       "aggregateErrors": [
traefik-cf-ddns-1  |         {
traefik-cf-ddns-1  |           "type": "Object",
traefik-cf-ddns-1  |           "message": "No route for that URI",
traefik-cf-ddns-1  |           "stack":
traefik-cf-ddns-1  |               
traefik-cf-ddns-1  |           "code": 7000
traefik-cf-ddns-1  |         }
traefik-cf-ddns-1  |       ],
traefik-cf-ddns-1  |       "errors": [
traefik-cf-ddns-1  |         {
traefik-cf-ddns-1  |           "code": 7000,
traefik-cf-ddns-1  |           "message": "No route for that URI"
traefik-cf-ddns-1  |         }
traefik-cf-ddns-1  |       ]
traefik-cf-ddns-1  |     }
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] INFO (28): Cloudflare DDNS end
```

**Comment by yorickdowne** [comment]
With variables filled in it's

```
services:
  cf-ddns:
    environment:
      CF_DNS__AUTH__SCOPED_TOKEN: myToken
      CF_DNS__DOMAINS_0__CREATE: "true"
      CF_DNS__DOMAINS_0__NAME: eth-testing.cryptomanufaktur.net
      CF_DNS__DOMAINS_0__PROXIED: "false"
      CF_DNS__DOMAINS_0__TYPE: A
      CF_DNS__DOMAINS_0__ZONE_ID: 9da992a125c29f389d79c564f6616bd0
      CF_DNS__DOMAINS_0__ZONE_NAME: cryptomanufaktur.net
      CF_DNS__DOMAINS_1__CREATE: "true"
      CF_DNS__DOMAINS_1__NAME: eth-testing.cryptomanufaktur.net
      CF_DNS__DOMAINS_1__PROXIED: "false"
      CF_DNS__DOMAINS_1__TYPE: AAAA
      CF_DNS__DOMAINS_1__ZONE_ID: 9da992a125c29f389d79c564f6616bd0
      CF_DNS__DOMAINS_1__ZONE_NAME: cryptomanufaktur.net
      CF_DNS__LOG_LEVEL: debug
    image: ghcr.io/joshuaavalon/cloudflare-ddns:3.1.0

```
