### ISSUE TITLE
[Bug] Debug logs do not output configurations

### ISSUE THREAD

**Issue by yorickdowne** [joshuaavalon/docker-cloudflare#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.2.2

### Describe The Bug

docker-cloudflare 3.2.2 no longer outputs the configuration with debug logs, although it announces it will. Downgrading to 3.1.0 resolves this issue

### Steps To Reproduce

Run version 3.2.2 with debug logging

### Expected Behavior

Configuration details are output to console log

### YAML Configuration

```
services:
  cf-ddns:
    environment:
      CF_DNS__AUTH__SCOPED_TOKEN: myToken
      CF_DNS__DOMAINS_0__CREATE: "true"
      CF_DNS__DOMAINS_0__NAME: eth-testing.cryptomanufaktur.net
      CF_DNS__DOMAINS_0__PROXIED: "false"
      CF_DNS__DOMAINS_0__TYPE: A
      CF_DNS__DOMAINS_0__ZONE_ID: 9da992a125c29f389d79c564f6616bd0
      CF_DNS__DOMAINS_0__ZONE_NAME: cryptomanufaktur.net
      CF_DNS__DOMAINS_1__CREATE: "true"
      CF_DNS__DOMAINS_1__NAME: eth-testing.cryptomanufaktur.net
      CF_DNS__DOMAINS_1__PROXIED: "false"
      CF_DNS__DOMAINS_1__TYPE: AAAA
      CF_DNS__DOMAINS_1__ZONE_ID: 9da992a125c29f389d79c564f6616bd0
      CF_DNS__DOMAINS_1__ZONE_NAME: cryptomanufaktur.net
      CF_DNS__LOG_LEVEL: debug
    image: ghcr.io/joshuaavalon/cloudflare-ddns:3
```

### Relevant Output Log

```shell
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] DEBUG (28): Running with the following configuration
traefik-cf-ddns-1  | [2023-07-25A09:00:02+0000] ERROR (28): Failed to update eth-testing.cryptomanufaktur.net
```
