### ISSUE TITLE
[Bug] Issues updating records within recent versions 

### ISSUE THREAD

**Issue by chrxmvtik** [joshuaavalon/docker-cloudflare#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.2.3

### Describe The Bug

Recent version crashes while trying to update records

```js
 err: {
      "type": "CloudflareApiError",
      "message": "Api Error from Cloudflare. Errors: \n{\"code\":10000,\"message\":\"POST method not allowed for the api_token authentication scheme\"}",
      "stack":
          Error: Api Error from Cloudflare. Errors: 
          {"code":10000,"message":"POST method not allowed for the api_token authentication scheme"}
              at file:///app/packages/api/lib/create-api/index.js:38:19
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async update (file:///app/packages/app/lib/api.js:47:17)
              at async updateOrCreate (file:///app/packages/app/lib/api.js:85:20)
              at async updateDomain (file:///app/packages/app/lib/index.js:15:20)
              at async file:///app/packages/app/lib/index.js:44:28
              at async Promise.all (index 0)
              at async updateDnsRecords (file:///app/packages/app/lib/index.js:54:5)
              at async main (file:///app/packages/app/lib/index.js:74:9)
              at async file:///app/index.mjs:5:1
      "aggregateErrors": [
        {
          "type": "Object",
          "message": "POST method not allowed for the api_token authentication scheme",
          "stack":
              
          "code": 10000
        }
      ],
      "errors": [
        {
          "code": 10000,
          "message": "POST method not allowed for the api_token authentication scheme"
        }
      ]
    }
```

### Steps To Reproduce

Use latest version (3.2.3) with config that worked before - works fine with 3.2.0.

### Expected Behavior

No issue while sending a request to cloudflare.

**Comment by joshuaavalon** [comment]
I cannot reproduce your issue, Please make sure you configuration and your permission of the API token is correct.

**Comment by chrxmvtik** [comment]
> I cannot reproduce your issue, Please make sure you configuration and your permission of the API token is correct.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-config
  namespace: cf
data:
  config.yaml: |
    api: https://api.cloudflare.com/client/v4/
    logLevel: info
    auth:
      scopedToken: XXXXXXXXXXXXXXXXXXXXXXX
    domains:
    - name: xxx.domain.a
      type: A
      proxied: true
      create: true
      zoneId: 23b4a2bb4cccxxxxxxxxxxxxxxxxxxxxx
    - name: xxx.xxx.domain.b
      type: A
      proxied: true
      create: true
      zoneId: a7c1f39f37895d33xxxxxxxxxxxxxxx
    - name: xxxx.domain.c
      type: A
      proxied: true
      create: true
      zoneId: a7c1f39f37895d331xxxxxxxxxxxxx
    ipv4:
    - type: ini
      url: https://1.1.1.1/cdn-cgi/trace
      fields:
      - ip
    - type: json
      url: https://api.ipify.org?format=json
      fields:
      - ip
    ipv6:
    - type: ini
      url: https://[2606:4700:4700::1111]/cdn-cgi/trace
      fields:
      - ip
    - type: json
      url: https://api6.ipify.org?format=json
      fields:
      - ip
    echoParsers:
    - resolve: "@cloudflare-ddns/ip-echo-parser-ini"
      alias: ini
    - resolve: "@cloudflare-ddns/ip-echo-parser-json"
      alias: json
    - resolve: "@cloudflare-ddns/ip-echo-parser-text"
      alias: text
```

My config is correct I am using mulitple domains, as I stated in the description of the issue when using version 3.2.0 there are no issues at all, but after upgrading to newer versions, issue appears.
