### ISSUE TITLE
Empty webhook configuration from environment variables

### ISSUE THREAD

**Issue by brettinternet** [joshuaavalon/docker-cloudflare#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.3.0

### Describe The Bug

I am unable to set webhook configuration from environment variables.

I have used the `latest` tag for `3.3.0` and also the most recent `sha-2f048d4`.

### Steps To Reproduce

```yaml
services:
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:latest
    environment:
      CF_DNS__CRON: "*/10 * * * *"
      CF_DNS__LOG_LEVEL: debug
      CF_DNS__AUTH__SCOPED_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      CF_DNS__DOMAINS_0__ZONE_NAME: "${MY_DOMAIN}"
      CF_DNS__DOMAINS_0__ZONE_ID: "${CLOUDFLARE_MY_DOMAIN_ZONE_ID}"
      CF_DNS__DOMAINS_0__NAME: "ip.${MY_DOMAIN}"
      CF_DNS__DOMAINS_0__PROXIED: "false"
      CF_DNS__DOMAINS_0__CREATE: "true"
      CF_DNS__DOMAINS_0__TYPE: A
      CF_DNS__DOMAINS_0__WEBHOOK_0__RUN: "http://healthchecks:8000/ping/${HEALTHCHECKS_DDNS_UUID}/start"
      CF_DNS__DOMAINS_0__WEBHOOK_0__SUCCESS: "http://healthchecks:8000/ping/${HEALTHCHECKS_DDNS_UUID}"
      CF_DNS__DOMAINS_0__WEBHOOK_0__FAILURE: "http://healthchecks:8000/ping/${HEALTHCHECKS_DDNS_UUID}/fail"
```

### Expected Behavior

Configure the webhook with environment variables.

### Relevant Output Log

```shell
DEBUG: Running with the following configuration
    config: {
      "api": "https://api.cloudflare.com/client/v4/",
      "timeout": 5000,
      "domains": [
{
          "name": "ip.example.com",
          "type": "A",
          "proxied": false,
          "create": true,
          "zoneId": "zoneid",
          "zoneName": "example.com",
          "webhook": {}
}
…
```
```
